import type { ItemCategory } from './types';

// Minecraft 1.16.x items organized by Creative Inventory tabs (excluding 'all')
export const MINECRAFT_ITEMS: Record<Exclude<ItemCategory, 'all'>, string[]> = {
  // 建築ブロック (Building Blocks)
  building_blocks: [
    'minecraft:dirt',
    'minecraft:cobblestone',
    'minecraft:stone',
    'minecraft:granite',
    'minecraft:diorite',
    'minecraft:andesite',
    'minecraft:grass_block',
    'minecraft:oak_planks',
    'minecraft:spruce_planks',
    'minecraft:birch_planks',
    'minecraft:jungle_planks',
    'minecraft:acacia_planks',
    'minecraft:dark_oak_planks',
    'minecraft:crimson_planks',
    'minecraft:warped_planks',
    'minecraft:oak_log',
    'minecraft:spruce_log',
    'minecraft:birch_log',
    'minecraft:jungle_log',
    'minecraft:acacia_log',
    'minecraft:dark_oak_log',
    'minecraft:crimson_stem',
    'minecraft:warped_stem',
    'minecraft:stripped_oak_log',
    'minecraft:stripped_spruce_log',
    'minecraft:stripped_birch_log',
    'minecraft:stripped_jungle_log',
    'minecraft:stripped_acacia_log',
    'minecraft:stripped_dark_oak_log',
    'minecraft:stripped_crimson_stem',
    'minecraft:stripped_warped_stem',
    'minecraft:oak_wood',
    'minecraft:spruce_wood',
    'minecraft:birch_wood',
    'minecraft:jungle_wood',
    'minecraft:acacia_wood',
    'minecraft:dark_oak_wood',
    'minecraft:crimson_hyphae',
    'minecraft:warped_hyphae',
    'minecraft:sand',
    'minecraft:red_sand',
    'minecraft:gravel',
    'minecraft:netherrack',
    'minecraft:soul_sand',
    'minecraft:soul_soil',
    'minecraft:basalt',
    'minecraft:blackstone',
    'minecraft:gilded_blackstone',
    'minecraft:magma_block',
    'minecraft:obsidian',
    'minecraft:crying_obsidian',
    'minecraft:end_stone',
    'minecraft:nether_bricks',
    'minecraft:red_nether_bricks',
    'minecraft:glowstone',
    'minecraft:prismarine',
    'minecraft:prismarine_bricks',
    'minecraft:dark_prismarine',
    'minecraft:sea_lantern',
  ],

  // 装飾ブロック (Decoration Blocks)
  decorations: [
    'minecraft:torch',
    'minecraft:soul_torch',
    'minecraft:crafting_table',
    'minecraft:furnace',
    'minecraft:chest',
    'minecraft:trapped_chest',
    'minecraft:ender_chest',
    'minecraft:barrel',
    'minecraft:smoker',
    'minecraft:blast_furnace',
    'minecraft:white_shulker_box',
    'minecraft:orange_shulker_box',
    'minecraft:magenta_shulker_box',
    'minecraft:light_blue_shulker_box',
    'minecraft:yellow_shulker_box',
    'minecraft:lime_shulker_box',
    'minecraft:pink_shulker_box',
    'minecraft:gray_shulker_box',
    'minecraft:light_gray_shulker_box',
    'minecraft:cyan_shulker_box',
    'minecraft:purple_shulker_box',
    'minecraft:blue_shulker_box',
    'minecraft:brown_shulker_box',
    'minecraft:green_shulker_box',
    'minecraft:red_shulker_box',
    'minecraft:black_shulker_box',
    'minecraft:white_bed',
    'minecraft:orange_bed',
    'minecraft:magenta_bed',
    'minecraft:light_blue_bed',
    'minecraft:yellow_bed',
    'minecraft:lime_bed',
    'minecraft:pink_bed',
    'minecraft:gray_bed',
    'minecraft:light_gray_bed',
    'minecraft:cyan_bed',
    'minecraft:purple_bed',
    'minecraft:blue_bed',
    'minecraft:brown_bed',
    'minecraft:green_bed',
    'minecraft:red_bed',
    'minecraft:black_bed',
    'minecraft:oak_door',
    'minecraft:spruce_door',
    'minecraft:birch_door',
    'minecraft:jungle_door',
    'minecraft:acacia_door',
    'minecraft:dark_oak_door',
    'minecraft:crimson_door',
    'minecraft:warped_door',
    'minecraft:iron_door',
    'minecraft:ladder',
    'minecraft:scaffolding',
    'minecraft:oak_fence',
    'minecraft:oak_fence_gate',
    'minecraft:tnt',
    'minecraft:bookshelf',
  ],

  // レッドストーン (Redstone)
  redstone: [
    'minecraft:redstone',
    'minecraft:redstone_torch',
    'minecraft:redstone_block',
    'minecraft:repeater',
    'minecraft:comparator',
    'minecraft:lever',
    'minecraft:stone_button',
    'minecraft:oak_button',
    'minecraft:iron_trapdoor',
    'minecraft:oak_trapdoor',
    'minecraft:oak_pressure_plate',
    'minecraft:stone_pressure_plate',
    'minecraft:dispenser',
    'minecraft:dropper',
    'minecraft:piston',
    'minecraft:sticky_piston',
    'minecraft:hopper',
    'minecraft:observer',
    'minecraft:target',
  ],

  // 交通 (Transportation)
  transportation: [
    'minecraft:oak_boat',
    'minecraft:spruce_boat',
    'minecraft:birch_boat',
    'minecraft:jungle_boat',
    'minecraft:acacia_boat',
    'minecraft:dark_oak_boat',
    'minecraft:minecart',
    'minecraft:chest_minecart',
    'minecraft:furnace_minecart',
    'minecraft:tnt_minecart',
    'minecraft:hopper_minecart',
    'minecraft:rail',
    'minecraft:powered_rail',
    'minecraft:detector_rail',
    'minecraft:activator_rail',
    'minecraft:saddle',
    'minecraft:carrot_on_a_stick',
    'minecraft:warped_fungus_on_a_stick',
  ],

  // 雑貨 (Miscellaneous)
  miscellaneous: [
    'minecraft:stick',
    'minecraft:coal',
    'minecraft:charcoal',
    'minecraft:iron_ingot',
    'minecraft:gold_ingot',
    'minecraft:diamond',
    'minecraft:emerald',
    'minecraft:iron_nugget',
    'minecraft:gold_nugget',
    'minecraft:lapis_lazuli',
    'minecraft:flint',
    'minecraft:string',
    'minecraft:feather',
    'minecraft:gunpowder',
    'minecraft:wheat',
    'minecraft:wheat_seeds',
    'minecraft:egg',
    'minecraft:leather',
    'minecraft:bone',
    'minecraft:bone_meal',
    'minecraft:clay_ball',
    'minecraft:brick',
    'minecraft:nether_brick',
    'minecraft:nether_wart',
    'minecraft:sugar_cane',
    'minecraft:paper',
    'minecraft:book',
    'minecraft:slime_ball',
    'minecraft:ender_pearl',
    'minecraft:blaze_rod',
    'minecraft:blaze_powder',
    'minecraft:magma_cream',
    'minecraft:ender_eye',
    'minecraft:ghast_tear',
    'minecraft:glistering_melon_slice',
    'minecraft:spider_eye',
    'minecraft:fermented_spider_eye',
    'minecraft:dragon_breath',
    'minecraft:netherite_scrap',
    'minecraft:netherite_ingot',
    'minecraft:water_bucket',
    'minecraft:lava_bucket',
    'minecraft:milk_bucket',
    'minecraft:bucket',
    'minecraft:shears',
    'minecraft:flint_and_steel',
    'minecraft:fire_charge',
    'minecraft:fishing_rod',
    'minecraft:compass',
    'minecraft:clock',
    'minecraft:name_tag',
    'minecraft:lead',
    'minecraft:map',
  ],

  // 食料 (Foodstuffs)
  foodstuffs: [
    'minecraft:apple',
    'minecraft:golden_apple',
    'minecraft:enchanted_golden_apple',
    'minecraft:melon_slice',
    'minecraft:sweet_berries',
    'minecraft:glow_berries',
    'minecraft:carrot',
    'minecraft:golden_carrot',
    'minecraft:potato',
    'minecraft:baked_potato',
    'minecraft:poisonous_potato',
    'minecraft:beetroot',
    'minecraft:dried_kelp',
    'minecraft:beef',
    'minecraft:cooked_beef',
    'minecraft:porkchop',
    'minecraft:cooked_porkchop',
    'minecraft:mutton',
    'minecraft:cooked_mutton',
    'minecraft:chicken',
    'minecraft:cooked_chicken',
    'minecraft:rabbit',
    'minecraft:cooked_rabbit',
    'minecraft:cod',
    'minecraft:cooked_cod',
    'minecraft:salmon',
    'minecraft:cooked_salmon',
    'minecraft:tropical_fish',
    'minecraft:pufferfish',
    'minecraft:bread',
    'minecraft:cookie',
    'minecraft:cake',
    'minecraft:pumpkin_pie',
    'minecraft:rotten_flesh',
    'minecraft:spider_eye',
    'minecraft:mushroom_stew',
    'minecraft:rabbit_stew',
    'minecraft:suspicious_stew',
  ],

  // 道具 (Tools)
  tools: [
    'minecraft:wooden_pickaxe',
    'minecraft:wooden_axe',
    'minecraft:wooden_shovel',
    'minecraft:wooden_hoe',
    'minecraft:stone_pickaxe',
    'minecraft:stone_axe',
    'minecraft:stone_shovel',
    'minecraft:stone_hoe',
    'minecraft:iron_pickaxe',
    'minecraft:iron_axe',
    'minecraft:iron_shovel',
    'minecraft:iron_hoe',
    'minecraft:golden_pickaxe',
    'minecraft:golden_axe',
    'minecraft:golden_shovel',
    'minecraft:golden_hoe',
    'minecraft:diamond_pickaxe',
    'minecraft:diamond_axe',
    'minecraft:diamond_shovel',
    'minecraft:diamond_hoe',
    'minecraft:netherite_pickaxe',
    'minecraft:netherite_axe',
    'minecraft:netherite_shovel',
    'minecraft:netherite_hoe',
  ],

  // 戦闘 (Combat)
  combat: [
    'minecraft:wooden_sword',
    'minecraft:stone_sword',
    'minecraft:iron_sword',
    'minecraft:golden_sword',
    'minecraft:diamond_sword',
    'minecraft:netherite_sword',
    'minecraft:bow',
    'minecraft:crossbow',
    'minecraft:arrow',
    'minecraft:spectral_arrow',
    'minecraft:tipped_arrow',
    'minecraft:trident',
    'minecraft:shield',
    'minecraft:leather_helmet',
    'minecraft:leather_chestplate',
    'minecraft:leather_leggings',
    'minecraft:leather_boots',
    'minecraft:chainmail_helmet',
    'minecraft:chainmail_chestplate',
    'minecraft:chainmail_leggings',
    'minecraft:chainmail_boots',
    'minecraft:iron_helmet',
    'minecraft:iron_chestplate',
    'minecraft:iron_leggings',
    'minecraft:iron_boots',
    'minecraft:golden_helmet',
    'minecraft:golden_chestplate',
    'minecraft:golden_leggings',
    'minecraft:golden_boots',
    'minecraft:diamond_helmet',
    'minecraft:diamond_chestplate',
    'minecraft:diamond_leggings',
    'minecraft:diamond_boots',
    'minecraft:netherite_helmet',
    'minecraft:netherite_chestplate',
    'minecraft:netherite_leggings',
    'minecraft:netherite_boots',
    'minecraft:turtle_helmet',
  ],

  // 醸造 (Brewing)
  brewing: [
    'minecraft:potion',
    'minecraft:splash_potion',
    'minecraft:lingering_potion',
    'minecraft:brewing_stand',
    'minecraft:cauldron',
    'minecraft:blaze_powder',
    'minecraft:dragon_breath',
    'minecraft:glass_bottle',
    'minecraft:nether_wart',
    'minecraft:redstone',
    'minecraft:glowstone_dust',
    'minecraft:fermented_spider_eye',
    'minecraft:magma_cream',
    'minecraft:sugar',
    'minecraft:rabbit_foot',
    'minecraft:glistering_melon_slice',
    'minecraft:spider_eye',
    'minecraft:pufferfish',
    'minecraft:golden_carrot',
    'minecraft:ghast_tear',
    'minecraft:turtle_helmet',
  ],
};

// Helper function to get all items
export function getAllItems(): string[] {
  return Object.values(MINECRAFT_ITEMS).flat();
}

// Helper function to get items by category
export function getItemsByCategory(category: ItemCategory): string[] {
  if (category === 'all') {
    return getAllItems();
  }
  return MINECRAFT_ITEMS[category] || [];
}

// Category definitions for the UI (based on Minecraft 1.16 Creative Inventory tabs)
export const ITEM_CATEGORIES = [
  { id: 'all', name: 'すべて' },
  { id: 'building_blocks', name: '建築ブロック' },
  { id: 'decorations', name: '装飾ブロック' },
  { id: 'redstone', name: 'レッドストーン' },
  { id: 'transportation', name: '交通' },
  { id: 'miscellaneous', name: '雑貨' },
  { id: 'foodstuffs', name: '食料' },
  { id: 'tools', name: '道具' },
  { id: 'combat', name: '戦闘' },
  { id: 'brewing', name: '醸造' },
] as const;
