/**
 * Mapping between Minecraft 1.16.1 potion effect IDs and texture variant numbers
 * Based on the order of textures generated by mc-texture-renderer
 */

export interface PotionEffectInfo {
  id: string;
  name: string;
  variant: number;
  duration?: string; // Effect duration (e.g., "3:00", "8:00")
}

export const POTION_EFFECTS: PotionEffectInfo[] = [
  { id: 'minecraft:water', name: '水入り瓶', variant: 1 },
  { id: 'minecraft:mundane', name: 'ありふれたポーション', variant: 2 },
  { id: 'minecraft:thick', name: '濃厚なポーション', variant: 3 },
  { id: 'minecraft:awkward', name: '奇妙なポーション', variant: 4 },
  { id: 'minecraft:night_vision', name: '暗視', variant: 5, duration: '3:00' },
  { id: 'minecraft:long_night_vision', name: '暗視', variant: 6, duration: '8:00' },
  { id: 'minecraft:invisibility', name: '透明化', variant: 7, duration: '3:00' },
  { id: 'minecraft:long_invisibility', name: '透明化', variant: 8, duration: '8:00' },
  { id: 'minecraft:leaping', name: '跳躍', variant: 9, duration: '3:00' },
  { id: 'minecraft:long_leaping', name: '跳躍', variant: 10, duration: '8:00' },
  { id: 'minecraft:strong_leaping', name: '跳躍', variant: 11, duration: '3:00' },
  { id: 'minecraft:fire_resistance', name: '火炎耐性', variant: 12, duration: '3:00' },
  { id: 'minecraft:long_fire_resistance', name: '火炎耐性', variant: 13, duration: '8:00' },
  { id: 'minecraft:swiftness', name: '俊敏', variant: 14, duration: '3:00' },
  { id: 'minecraft:long_swiftness', name: '俊敏', variant: 15, duration: '8:00' },
  { id: 'minecraft:strong_swiftness', name: '俊敏', variant: 16, duration: '3:00' },
  { id: 'minecraft:slowness', name: '鈍化', variant: 17, duration: '3:00' },
  { id: 'minecraft:long_slowness', name: '鈍化', variant: 18, duration: '8:00' },
  { id: 'minecraft:strong_slowness', name: '鈍化', variant: 19, duration: '3:00' },
  { id: 'minecraft:turtle_master', name: 'タートルマスター', variant: 20, duration: '3:00' },
  { id: 'minecraft:long_turtle_master', name: 'タートルマスター', variant: 21, duration: '8:00' },
  { id: 'minecraft:strong_turtle_master', name: 'タートルマスター', variant: 22, duration: '3:00' },
  { id: 'minecraft:water_breathing', name: '水中呼吸', variant: 23, duration: '3:00' },
  { id: 'minecraft:long_water_breathing', name: '水中呼吸', variant: 24, duration: '8:00' },
  { id: 'minecraft:healing', name: '治癒', variant: 25 },
  { id: 'minecraft:strong_healing', name: '治癒', variant: 26 },
  { id: 'minecraft:harming', name: 'ダメージ', variant: 27 },
  { id: 'minecraft:strong_harming', name: 'ダメージ', variant: 28 },
  { id: 'minecraft:poison', name: '毒', variant: 29, duration: '3:00' },
  { id: 'minecraft:long_poison', name: '毒', variant: 30, duration: '8:00' },
  { id: 'minecraft:strong_poison', name: '毒', variant: 31, duration: '3:00' },
  { id: 'minecraft:regeneration', name: '再生', variant: 32, duration: '3:00' },
  { id: 'minecraft:long_regeneration', name: '再生', variant: 33, duration: '8:00' },
  { id: 'minecraft:strong_regeneration', name: '再生', variant: 34, duration: '3:00' },
  { id: 'minecraft:strength', name: '力', variant: 35, duration: '3:00' },
  { id: 'minecraft:long_strength', name: '力', variant: 36, duration: '8:00' },
  { id: 'minecraft:strong_strength', name: '力', variant: 37, duration: '3:00' },
  { id: 'minecraft:weakness', name: '弱化', variant: 38, duration: '3:00' },
  { id: 'minecraft:long_weakness', name: '弱化', variant: 39, duration: '8:00' },
  { id: 'minecraft:slow_falling', name: '低速落下', variant: 40, duration: '3:00' },
  { id: 'minecraft:long_slow_falling', name: '低速落下', variant: 41, duration: '8:00' },
];

export const POTION_EFFECT_TO_TEXTURE: Record<string, number> = {
  // Water bottle / Mundane potions
  'minecraft:water': 1,
  'minecraft:mundane': 2,
  'minecraft:thick': 3,
  'minecraft:awkward': 4,

  // Night Vision
  'minecraft:night_vision': 5,
  'minecraft:long_night_vision': 6,

  // Invisibility
  'minecraft:invisibility': 7,
  'minecraft:long_invisibility': 8,

  // Leaping / Jump Boost
  'minecraft:leaping': 9,
  'minecraft:long_leaping': 10,
  'minecraft:strong_leaping': 11,

  // Fire Resistance
  'minecraft:fire_resistance': 12,
  'minecraft:long_fire_resistance': 13,

  // Swiftness / Speed
  'minecraft:swiftness': 14,
  'minecraft:long_swiftness': 15,
  'minecraft:strong_swiftness': 16,

  // Slowness
  'minecraft:slowness': 17,
  'minecraft:long_slowness': 18,
  'minecraft:strong_slowness': 19,

  // Turtle Master
  'minecraft:turtle_master': 20,
  'minecraft:long_turtle_master': 21,
  'minecraft:strong_turtle_master': 22,

  // Water Breathing
  'minecraft:water_breathing': 23,
  'minecraft:long_water_breathing': 24,

  // Healing / Instant Health
  'minecraft:healing': 25,
  'minecraft:strong_healing': 26,

  // Harming / Instant Damage
  'minecraft:harming': 27,
  'minecraft:strong_harming': 28,

  // Poison
  'minecraft:poison': 29,
  'minecraft:long_poison': 30,
  'minecraft:strong_poison': 31,

  // Regeneration
  'minecraft:regeneration': 32,
  'minecraft:long_regeneration': 33,
  'minecraft:strong_regeneration': 34,

  // Strength
  'minecraft:strength': 35,
  'minecraft:long_strength': 36,
  'minecraft:strong_strength': 37,

  // Weakness
  'minecraft:weakness': 38,
  'minecraft:long_weakness': 39,

  // Slow Falling
  'minecraft:slow_falling': 40,
  'minecraft:long_slow_falling': 41,
};

/**
 * Get the texture variant number for a potion effect
 * Returns undefined if the effect is not found
 */
export function getPotionTextureVariant(potionEffect: string | undefined): number | undefined {
  if (!potionEffect) return undefined;
  return POTION_EFFECT_TO_TEXTURE[potionEffect];
}

/**
 * Get potion effect information by ID
 */
export function getPotionEffectInfo(potionEffect: string | undefined): PotionEffectInfo | undefined {
  if (!potionEffect) return undefined;
  return POTION_EFFECTS.find(e => e.id === potionEffect);
}

/**
 * Format potion display name (e.g., "火炎耐性のスプラッシュポーション")
 */
export function formatPotionName(itemId: string, potionEffect: string | undefined): string {
  const effectInfo = getPotionEffectInfo(potionEffect);
  const effectName = effectInfo?.name || '不明';

  if (itemId === 'minecraft:splash_potion') {
    return `${effectName}のスプラッシュポーション`;
  } else if (itemId === 'minecraft:lingering_potion') {
    return `${effectName}の残留ポーション`;
  } else {
    return `${effectName}のポーション`;
  }
}

/**
 * Format potion effect with duration (e.g., "火炎耐性 (3:00)")
 */
export function formatPotionEffect(potionEffect: string | undefined): string {
  const effectInfo = getPotionEffectInfo(potionEffect);
  if (!effectInfo) return '不明';

  if (effectInfo.duration) {
    return `${effectInfo.name} (${effectInfo.duration})`;
  }
  return effectInfo.name;
}
