/**
 * Minecraft言語リスト（全言語）
 * Combobox用の value/label 形式
 */
export const MINECRAFT_LANGUAGES: { value: string; label: string }[] = [
  { value: 'af_za', label: 'Afrikaans (Suid-Afrika)' },
  { value: 'ar_sa', label: 'العربية (السعودية)' },
  { value: 'ast_es', label: 'Asturianu (España)' },
  { value: 'az_az', label: 'Azərbaycanca (Azərbaycan)' },
  { value: 'ba_ru', label: 'Башҡортса (Россия)' },
  { value: 'bar', label: 'Bairisch' },
  { value: 'be_by', label: 'Беларуская (Беларусь)' },
  { value: 'bg_bg', label: 'Български (България)' },
  { value: 'br_fr', label: 'Brezhoneg (Frañs)' },
  { value: 'brb', label: 'Barbadian' },
  { value: 'bs_ba', label: 'Bosanski (Bosna i Hercegovina)' },
  { value: 'ca_es', label: 'Català (Espanya)' },
  { value: 'cs_cz', label: 'Čeština (Česko)' },
  { value: 'cy_gb', label: 'Cymraeg (Y Deyrnas Unedig)' },
  { value: 'da_dk', label: 'Dansk (Danmark)' },
  { value: 'de_at', label: 'Deutsch (Österreich)' },
  { value: 'de_ch', label: 'Deutsch (Schweiz)' },
  { value: 'de_de', label: 'Deutsch (Deutschland)' },
  { value: 'el_gr', label: 'Ελληνικά (Ελλάδα)' },
  { value: 'en_au', label: 'English (Australia)' },
  { value: 'en_ca', label: 'English (Canada)' },
  { value: 'en_gb', label: 'English (United Kingdom)' },
  { value: 'en_nz', label: 'English (New Zealand)' },
  { value: 'en_pt', label: 'English (Pirate Speak)' },
  { value: 'en_ud', label: 'English (Upside Down)' },
  { value: 'en_us', label: 'English (United States)' },
  { value: 'enp', label: 'English (Anglish)' },
  { value: 'enws', label: 'English (Early Modern)' },
  { value: 'eo_uy', label: 'Esperanto (Urugvajo)' },
  { value: 'es_ar', label: 'Español (Argentina)' },
  { value: 'es_cl', label: 'Español (Chile)' },
  { value: 'es_ec', label: 'Español (Ecuador)' },
  { value: 'es_es', label: 'Español (España)' },
  { value: 'es_mx', label: 'Español (México)' },
  { value: 'es_uy', label: 'Español (Uruguay)' },
  { value: 'es_ve', label: 'Español (Venezuela)' },
  { value: 'et_ee', label: 'Eesti (Eesti)' },
  { value: 'eu_es', label: 'Euskara (Espainia)' },
  { value: 'fa_ir', label: 'فارسی (ایران)' },
  { value: 'fi_fi', label: 'Suomi (Suomi)' },
  { value: 'fil_ph', label: 'Filipino (Pilipinas)' },
  { value: 'fo_fo', label: 'Føroyskt (Føroyar)' },
  { value: 'fr_ca', label: 'Français (Canada)' },
  { value: 'fr_fr', label: 'Français (France)' },
  { value: 'fra_de', label: 'Fränkisch (Deutschland)' },
  { value: 'fur_it', label: 'Furlan (Italie)' },
  { value: 'fy_nl', label: 'Frysk (Nederlân)' },
  { value: 'ga_ie', label: 'Gaeilge (Éire)' },
  { value: 'gd_gb', label: 'Gàidhlig (An Rìoghachd Aonaichte)' },
  { value: 'gl_es', label: 'Galego (España)' },
  { value: 'haw_us', label: 'ʻŌlelo Hawaiʻi (ʻAmelika Hui Pū ʻIa)' },
  { value: 'he_il', label: 'עברית (ישראל)' },
  { value: 'hi_in', label: 'हिन्दी (भारत)' },
  { value: 'hr_hr', label: 'Hrvatski (Hrvatska)' },
  { value: 'hu_hu', label: 'Magyar (Magyarország)' },
  { value: 'hy_am', label: 'Հdelays(Delays' },
  { value: 'id_id', label: 'Bahasa Indonesia (Indonesia)' },
  { value: 'ig_ng', label: 'Igbo (Naịjịrịa)' },
  { value: 'io_en', label: 'Ido (Anglia)' },
  { value: 'is_is', label: 'Íslenska (Ísland)' },
  { value: 'isv', label: 'Interslavic' },
  { value: 'it_it', label: 'Italiano (Italia)' },
  { value: 'ja_jp', label: '日本語 (日本)' },
  { value: 'jbo_en', label: "la .lojban. (lb'anglia)" },
  { value: 'ka_ge', label: 'ქართული (საქართველო)' },
  { value: 'kk_kz', label: 'Қazaқsha (Қazaқstan)' },
  { value: 'kn_in', label: 'ಕನ್ನಡ (ಭಾರತ)' },
  { value: 'ko_kr', label: '한국어 (대한민국)' },
  { value: 'ksh', label: 'Kölsch' },
  { value: 'kw_gb', label: 'Kernewek (Rywvaneth Unys)' },
  { value: 'la_la', label: 'Latina (Imperium Romanum)' },
  { value: 'lb_lu', label: 'Lëtzebuergesch (Lëtzebuerg)' },
  { value: 'li_li', label: 'Limburgs (Limburg)' },
  { value: 'lmo', label: 'Lombard' },
  { value: 'lt_lt', label: 'Lietuvių (Lietuva)' },
  { value: 'lv_lv', label: 'Latviešu (Latvija)' },
  { value: 'lzh', label: '文言 (華夏)' },
  { value: 'mk_mk', label: 'Македонски (Македонија)' },
  { value: 'mn_mn', label: 'Монгол (Монгол Улс)' },
  { value: 'ms_my', label: 'Bahasa Melayu (Malaysia)' },
  { value: 'mt_mt', label: 'Malti (Malta)' },
  { value: 'nds_de', label: 'Plattdüütsch (Düütschland)' },
  { value: 'nl_be', label: 'Nederlands (België)' },
  { value: 'nl_nl', label: 'Nederlands (Nederland)' },
  { value: 'nn_no', label: 'Norsk nynorsk (Noreg)' },
  { value: 'no_no', label: 'Norsk bokmål (Norge)' },
  { value: 'oc_fr', label: 'Occitan (França)' },
  { value: 'ovd', label: 'Övdalsk' },
  { value: 'pl_pl', label: 'Polski (Polska)' },
  { value: 'pt_br', label: 'Português (Brasil)' },
  { value: 'pt_pt', label: 'Português (Portugal)' },
  { value: 'qya_aa', label: 'Quenya (Arda)' },
  { value: 'ro_ro', label: 'Română (România)' },
  { value: 'rpr', label: 'Ripoarisch' },
  { value: 'ru_ru', label: 'Русский (Россия)' },
  { value: 'se_no', label: 'Davvisámegiella (Norga)' },
  { value: 'sk_sk', label: 'Slovenčina (Slovensko)' },
  { value: 'sl_si', label: 'Slovenščina (Slovenija)' },
  { value: 'so_so', label: 'Soomaaliga (Soomaaliya)' },
  { value: 'sq_al', label: 'Shqip (Shqipëri)' },
  { value: 'sr_sp', label: 'Српски (Србија)' },
  { value: 'sv_se', label: 'Svenska (Sverige)' },
  { value: 'sxu', label: 'Saksisch' },
  { value: 'szl', label: 'Ślōnskŏ gŏdka' },
  { value: 'ta_in', label: 'தமிழ் (இந்தியா)' },
  { value: 'th_th', label: 'ไทย (ประเทศไทย)' },
  { value: 'tl_ph', label: 'Tagalog (Pilipinas)' },
  { value: 'tlh_aa', label: "tlhIngan Hol (tlhIngan wo')" },
  { value: 'tok', label: 'toki pona' },
  { value: 'tr_tr', label: 'Türkçe (Türkiye)' },
  { value: 'tt_ru', label: 'Татарча (Россия)' },
  { value: 'uk_ua', label: 'Українська (Україна)' },
  { value: 'val_es', label: 'Valencià (Espanya)' },
  { value: 'vec_it', label: 'Vèneto (Itàlia)' },
  { value: 'vi_vn', label: 'Tiếng Việt (Việt Nam)' },
  { value: 'yi_de', label: 'ייִדיש (דײַטשלאַנד)' },
  { value: 'yo_ng', label: 'Yorùbá (Nàìjíríà)' },
  { value: 'zh_cn', label: '简体中文 (中国大陆)' },
  { value: 'zh_hk', label: '繁體中文 (香港)' },
  { value: 'zh_tw', label: '繁體中文 (台灣)' },
  { value: 'zlm_arab', label: 'بهاس ملايو (مليسيا)' },
];

// 言語コードから言語名を引くためのマップを生成
const languageMap = new Map(
  MINECRAFT_LANGUAGES.map(lang => [lang.value.toLowerCase(), lang.label])
);

/**
 * 言語コードを言語名に変換する
 * @param languageCode 言語コード（例: "ja_jp"）
 * @returns 言語名（例: "日本語 (日本)"）、見つからない場合は元のコードを返す
 */
export function getLanguageName(languageCode: string | null | undefined): string {
  if (!languageCode) return '-';
  return languageMap.get(languageCode.toLowerCase()) || languageCode;
}
