import type { Finger } from '@/types/player';

// 利用可能なアクション一覧
export const ACTIONS = [
  { id: 'forward', label: '前進' },
  { id: 'back', label: '後退' },
  { id: 'left', label: '左移動' },
  { id: 'right', label: '右移動' },
  { id: 'jump', label: 'ジャンプ' },
  { id: 'sneak', label: 'スニーク' },
  { id: 'sprint', label: 'ダッシュ' },
  { id: 'inventory', label: 'インベントリ' },
  { id: 'swapHands', label: 'オフハンド持ち替え' },
  { id: 'drop', label: 'ドロップ' },
  { id: 'pickBlock', label: 'ブロック選択' },
  { id: 'chat', label: 'チャット' },
  { id: 'command', label: 'コマンド' },
  { id: 'togglePerspective', label: '視点変更' },
  { id: 'fullscreen', label: 'フルスクリーン' },
  { id: 'toggleHud', label: 'HUD非表示' },
  { id: 'playerList', label: 'プレイヤーリスト' },
  { id: 'reset', label: 'リセット' },
  ...Array.from({ length: 9 }, (_, i) => ({
    id: `hotbar${i + 1}`,
    label: `ホットバー${i + 1}`,
  })),
];

// 指の選択肢定義
export const FINGER_OPTIONS: { value: Finger; label: string; hand: 'left' | 'right' }[] = [
  { value: 'left-pinky', label: '左手 小指', hand: 'left' },
  { value: 'left-ring', label: '左手 薬指', hand: 'left' },
  { value: 'left-middle', label: '左手 中指', hand: 'left' },
  { value: 'left-index', label: '左手 人差し指', hand: 'left' },
  { value: 'left-thumb', label: '左手 親指', hand: 'left' },
  { value: 'right-thumb', label: '右手 親指', hand: 'right' },
  { value: 'right-index', label: '右手 人差し指', hand: 'right' },
  { value: 'right-middle', label: '右手 中指', hand: 'right' },
  { value: 'right-ring', label: '右手 薬指', hand: 'right' },
  { value: 'right-pinky', label: '右手 小指', hand: 'right' },
];

// リマップ可能なキー一覧
export const REMAPPABLE_KEYS = {
  '特殊': [
    { value: 'key.keyboard.disabled', label: '無効化（キーを押しても反応しない）' },
  ],
  '修飾キー': [
    { value: 'key.keyboard.left.shift', label: '左Shift' },
    { value: 'key.keyboard.right.shift', label: '右Shift' },
    { value: 'key.keyboard.left.control', label: '左Ctrl' },
    { value: 'key.keyboard.right.control', label: '右Ctrl' },
    { value: 'key.keyboard.left.alt', label: '左Alt' },
    { value: 'key.keyboard.right.alt', label: '右Alt' },
    { value: 'key.keyboard.caps.lock', label: 'Caps Lock' },
  ],
  '文字キー': [
    { value: 'key.keyboard.a', label: 'A' },
    { value: 'key.keyboard.b', label: 'B' },
    { value: 'key.keyboard.c', label: 'C' },
    { value: 'key.keyboard.d', label: 'D' },
    { value: 'key.keyboard.e', label: 'E' },
    { value: 'key.keyboard.f', label: 'F' },
    { value: 'key.keyboard.g', label: 'G' },
    { value: 'key.keyboard.h', label: 'H' },
    { value: 'key.keyboard.i', label: 'I' },
    { value: 'key.keyboard.j', label: 'J' },
    { value: 'key.keyboard.k', label: 'K' },
    { value: 'key.keyboard.l', label: 'L' },
    { value: 'key.keyboard.m', label: 'M' },
    { value: 'key.keyboard.n', label: 'N' },
    { value: 'key.keyboard.o', label: 'O' },
    { value: 'key.keyboard.p', label: 'P' },
    { value: 'key.keyboard.q', label: 'Q' },
    { value: 'key.keyboard.r', label: 'R' },
    { value: 'key.keyboard.s', label: 'S' },
    { value: 'key.keyboard.t', label: 'T' },
    { value: 'key.keyboard.u', label: 'U' },
    { value: 'key.keyboard.v', label: 'V' },
    { value: 'key.keyboard.w', label: 'W' },
    { value: 'key.keyboard.x', label: 'X' },
    { value: 'key.keyboard.y', label: 'Y' },
    { value: 'key.keyboard.z', label: 'Z' },
  ],
  '数字キー': [
    { value: 'key.keyboard.1', label: '1' },
    { value: 'key.keyboard.2', label: '2' },
    { value: 'key.keyboard.3', label: '3' },
    { value: 'key.keyboard.4', label: '4' },
    { value: 'key.keyboard.5', label: '5' },
    { value: 'key.keyboard.6', label: '6' },
    { value: 'key.keyboard.7', label: '7' },
    { value: 'key.keyboard.8', label: '8' },
    { value: 'key.keyboard.9', label: '9' },
    { value: 'key.keyboard.0', label: '0' },
  ],
  'ファンクションキー': [
    { value: 'key.keyboard.f1', label: 'F1' },
    { value: 'key.keyboard.f2', label: 'F2' },
    { value: 'key.keyboard.f3', label: 'F3' },
    { value: 'key.keyboard.f4', label: 'F4' },
    { value: 'key.keyboard.f5', label: 'F5' },
    { value: 'key.keyboard.f6', label: 'F6' },
    { value: 'key.keyboard.f7', label: 'F7' },
    { value: 'key.keyboard.f8', label: 'F8' },
    { value: 'key.keyboard.f9', label: 'F9' },
    { value: 'key.keyboard.f10', label: 'F10' },
    { value: 'key.keyboard.f11', label: 'F11' },
    { value: 'key.keyboard.f12', label: 'F12' },
    { value: 'key.keyboard.f13', label: 'F13' },
    { value: 'key.keyboard.f14', label: 'F14' },
    { value: 'key.keyboard.f15', label: 'F15' },
    { value: 'key.keyboard.f16', label: 'F16' },
    { value: 'key.keyboard.f17', label: 'F17' },
    { value: 'key.keyboard.f18', label: 'F18' },
    { value: 'key.keyboard.f19', label: 'F19' },
    { value: 'key.keyboard.f20', label: 'F20' },
  ],
  '記号キー': [
    { value: 'key.keyboard.comma', label: ', (コンマ)' },
    { value: 'key.keyboard.period', label: '. (ピリオド)' },
    { value: 'key.keyboard.slash', label: '/ (スラッシュ)' },
    { value: 'key.keyboard.semicolon', label: '; (セミコロン)' },
    { value: 'key.keyboard.apostrophe', label: '\' (アポストロフィ)' },
    { value: 'key.keyboard.left.bracket', label: '[ (左角括弧)' },
    { value: 'key.keyboard.right.bracket', label: '] (右角括弧)' },
    { value: 'key.keyboard.minus', label: '- (マイナス)' },
    { value: 'key.keyboard.equal', label: '= (イコール)' },
    { value: 'key.keyboard.grave.accent', label: '` (グレイヴ)' },
    { value: 'key.keyboard.backslash', label: '\\ (バックスラッシュ)' },
  ],
  '特殊キー': [
    { value: 'key.keyboard.space', label: 'スペース' },
    { value: 'key.keyboard.enter', label: 'Enter' },
    { value: 'key.keyboard.tab', label: 'Tab' },
    { value: 'key.keyboard.backspace', label: 'Backspace' },
    { value: 'key.keyboard.escape', label: 'Esc' },
  ],
  '日本語キーボード': [
    { value: 'key.keyboard.nonconvert', label: '無変換' },
    { value: 'key.keyboard.convert', label: '変換' },
    { value: 'key.keyboard.kana', label: 'かな' },
  ],
  '矢印キー': [
    { value: 'key.keyboard.up', label: '↑' },
    { value: 'key.keyboard.down', label: '↓' },
    { value: 'key.keyboard.left', label: '←' },
    { value: 'key.keyboard.right', label: '→' },
  ],
  '編集キー': [
    { value: 'key.keyboard.insert', label: 'Insert' },
    { value: 'key.keyboard.delete', label: 'Delete' },
    { value: 'key.keyboard.home', label: 'Home' },
    { value: 'key.keyboard.end', label: 'End' },
    { value: 'key.keyboard.page.up', label: 'Page Up' },
    { value: 'key.keyboard.page.down', label: 'Page Down' },
  ],
  'テンキー': [
    { value: 'key.keyboard.keypad.0', label: 'テンキー 0' },
    { value: 'key.keyboard.keypad.1', label: 'テンキー 1' },
    { value: 'key.keyboard.keypad.2', label: 'テンキー 2' },
    { value: 'key.keyboard.keypad.3', label: 'テンキー 3' },
    { value: 'key.keyboard.keypad.4', label: 'テンキー 4' },
    { value: 'key.keyboard.keypad.5', label: 'テンキー 5' },
    { value: 'key.keyboard.keypad.6', label: 'テンキー 6' },
    { value: 'key.keyboard.keypad.7', label: 'テンキー 7' },
    { value: 'key.keyboard.keypad.8', label: 'テンキー 8' },
    { value: 'key.keyboard.keypad.9', label: 'テンキー 9' },
    { value: 'key.keyboard.keypad.add', label: 'テンキー +' },
    { value: 'key.keyboard.keypad.subtract', label: 'テンキー -' },
    { value: 'key.keyboard.keypad.multiply', label: 'テンキー *' },
    { value: 'key.keyboard.keypad.divide', label: 'テンキー /' },
    { value: 'key.keyboard.keypad.decimal', label: 'テンキー .' },
    { value: 'key.keyboard.keypad.enter', label: 'テンキー Enter' },
    { value: 'key.keyboard.keypad.equal', label: 'テンキー =' },
  ],
  '国際キー / 特殊文字': [
    { value: 'key.keyboard.world.1', label: 'World 1 (汎用特殊キー1)' },
    { value: 'key.keyboard.world.2', label: 'World 2 (汎用特殊キー2)' },
    { value: 'key.keyboard.section', label: '§ (セクション)' },
  ],
  '北欧語・ドイツ語キー': [
    { value: 'key.keyboard.ae', label: 'æ (AE合字)' },
    { value: 'key.keyboard.oe', label: 'ø (O with Stroke)' },
    { value: 'key.keyboard.aa', label: 'å (A with Ring)' },
    { value: 'key.keyboard.a.umlaut', label: 'ä (A Umlaut)' },
    { value: 'key.keyboard.o.umlaut', label: 'ö (O Umlaut)' },
    { value: 'key.keyboard.u.umlaut', label: 'ü (U Umlaut)' },
    { value: 'key.keyboard.eszett', label: 'ß (Eszett)' },
  ],
  'フランス語・その他の国際キー': [
    { value: 'key.keyboard.e.acute', label: 'é (E Acute)' },
    { value: 'key.keyboard.e.grave', label: 'è (E Grave)' },
    { value: 'key.keyboard.a.grave', label: 'à (A Grave)' },
    { value: 'key.keyboard.c.cedilla', label: 'ç (C Cedilla)' },
    { value: 'key.keyboard.n.tilde', label: 'ñ (N Tilde)' },
  ],
  'マウスボタン': [
    { value: 'key.mouse.left', label: 'マウス左' },
    { value: 'key.mouse.right', label: 'マウス右' },
    { value: 'key.mouse.middle', label: 'マウスホイール' },
    { value: 'key.mouse.4', label: 'マウス4' },
    { value: 'key.mouse.5', label: 'マウス5' },
  ],
};

// REMAPPABLE_KEYSをCombobox用のフラット配列に変換
export const REMAPPABLE_KEYS_OPTIONS = Object.entries(REMAPPABLE_KEYS).flatMap(([category, keys]) =>
  keys.map(key => ({ value: key.value, label: key.label, category }))
);

// 外部ツールアクションのプリセット定義
export const EXTERNAL_TOOL_ACTIONS = [
  { value: 'ThinBT', label: 'ThinBT' },
  { value: 'Wide', label: 'Wide' },
  { value: 'Zoom', label: 'Zoom' },
  { value: 'マウス感度切替', label: 'マウス感度切替' },
  { value: 'Ninb: リセット', label: 'Ninb: リセット' },
  { value: 'Ninb: Undo', label: 'Ninb: Undo' },
  { value: 'Ninb: Redo', label: 'Ninb: Redo' },
  { value: 'Ninb: ロック', label: 'Ninb: ロック' },
  { value: 'Ninb: +0.01', label: 'Ninb: +0.01' },
  { value: 'Ninb: -0.01', label: 'Ninb: -0.01' },
  { value: 'Ninb: 表示切替', label: 'Ninb: 表示切替' },
  { value: 'Ninb: Blue Boat', label: 'Ninb: Blue Boat' },
  { value: 'SeedQueue: Reset All', label: 'SeedQueue: Reset All' },
  { value: 'SeedQueue: Play Instance', label: 'SeedQueue: Play Instance' },
  { value: 'SeedQueue: Lock Instance', label: 'SeedQueue: Lock Instance' },
  { value: 'SeedQueue: Play Next Lock', label: 'SeedQueue: Play Next Lock' },
];
